### ISSUE TITLE
NuGetReference Switcher is blocking VS Input

### ISSUE THREAD

**Issue by squadwuschel** [RSuter/NuGetReferenceSwitcher#12]
Hello,

when I use the NuGet Reference Switcher in VS 2013 newest Updates installed inkluding Resharper 9.2.x. then after opening the Switcher Window and Applying a switch after that all shortcuts in VS are blocked I can't debug with F5 and so on. And when I want to close VS the following message shows up. "The userinput is blocked, .... by a active modal window or a task ...."

![image](https://cloud.githubusercontent.com/assets/1572878/11739374/40aedf50-9feb-11e5-86ca-d2598a5b8596.png)

**Comment by rsuter** [comment]
I think it was fixed? See https://github.com/rsuter/NuGetReferenceSwitcher/issues/3

**Comment by slaneyrw** [comment]
I've just installed v1.7 for VS2015 (with Update 1) and started getting this issue

**Comment by wbradney** [comment]
I'm getting this with 1.7 also

**Comment by GrimaceOfDespair** [comment]
Confirming issue with v1.7 @ VS2015

**Comment by Miedon** [comment]
I'm getting the same Problem. V. 1.7 Visual Studio 2015

**Comment by rsuter** [comment]
Can you provide a sample solution where I can reproduce this? My solutions work as expected...

**Comment by rsuter** [comment]
Do you think this is the solution?https://github.com/MrDoomBringer/NuGetReferenceSwitcher/commit/7b4f716672707e23abe385f42107120978343573

**Comment by gravidThoughts** [comment]
Having the same issue v 1.7 Visual Studio 2015 Professional Update 3.

**Comment by gravidThoughts** [comment]
@rsuter make a branch for a build with that pull request and I will test it in a fairly complex solution.

**Comment by GrimaceOfDespair** [comment]
@gravidThoughts As far as I can tell, the Save was already commented out by this commit: https://github.com/rsuter/NuGetReferenceSwitcher/commit/b055bc1aa7adf405899e6954010483cfc7b7dc8b

To no avail in my case

**Comment by miketonguk** [comment]
Just adding a +1 as it's happening for me too.  Version info below.

Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Professional

LightSwitch for Visual Studio 2015   00322-40000-00000-AA648
Microsoft LightSwitch for Visual Studio 2015

Microsoft Visual Studio Tools for Applications 2015   00322-40000-00000-AA648
Microsoft Visual Studio Tools for Applications 2015

Visual Basic 2015   00322-40000-00000-AA648
Microsoft Visual Basic 2015

Visual C# 2015   00322-40000-00000-AA648
Microsoft Visual C# 2015

Visual C++ 2015   00322-40000-00000-AA648
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   7.14.01128.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11107.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitExtensions   1.0
Git Extensions is a graphical user interface for Git that allows you to control Git without using the command-line

HasherCommand Extension   1.0
HasherCommand Visual Studio Extension Detailed Info

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 2016.2.2    Build 106.0.20160913.91321
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2016 JetBrains, Inc.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

NuGet References   1.0
Save time by managing your NuGet references right from the Solution Explorer packages.config

NuGetReferenceSwitcher   1.0
Information about my package

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.60519.0
Microsoft SQL Server Data Tools

TypeScript   1.8.36.0
TypeScript tools for Visual Studio

**Comment by GrimaceOfDespair** [comment]
We just discovered something that might light this up: we used to apply the tool within a project that was under TFS version control. We have now switched over to Git, and the UI does not block anymore.

I can think of a lot now that might cause the issue, but I just wanted to add this at least.

**Comment by miketonguk** [comment]
Can confirm, problem went away when switching to git for source control.

**Comment by rsuter** [comment]
Ok, this makes sense... is there any way to work around this problem?
