### ISSUE TITLE
VS2017 Support

### ISSUE THREAD

**Issue by niemyjski** [rsuter/NuGetReferenceSwitcher#21]
It would be super nice if this could be updated for VS2017!

**Comment by ejsmith** [comment]
Yes, please! I have been using this tool a lot and really want it on VS2017.

**Comment by pantonis** [comment]
I agree we need this extension for VS2017. This is by far the most useful plugin I have ever used.

**Comment by rsuter** [comment]
Upgrading to VS2017 should be relatively simple... but we also should upgrade it so that it also supports the new MSBuild Projects (ie .net core csproj)

**Comment by rsuter** [comment]
I already have a working version for vs2017, i hope to release it soon... for supporting the new tooling, I need your help

**Comment by rsuter** [comment]
I've added the VS2017 project, but somehow the projects cannot be loaded...

https://github.com/rsuter/NuGetReferenceSwitcher/commit/8682282072c08d525244421046e6860f73da54dd

Has anyone an idea?

**Comment by mterwoord** [comment]
You mean, visual studio has your extension loaded, but it doesn't show it? VS2017 has a reworked settings system. No more normal registry....

**Comment by rsuter** [comment]
Yes, the menu entry shows up, the ui launches but it cannot load the projects of the loaded solution... And debugging is a pita because all is based on com obj.

**Comment by rsuter** [comment]
Ok, with the latest VS 2017 update it seems to work.. here is the debug/test version... will do some more tests and release it via VS marketplace. This vsix is for everyone who cant wait (like me) :-)


[NuGetReferenceSwitcher.zip](https://github.com/rsuter/NuGetReferenceSwitcher/files/894700/NuGetReferenceSwitcher.zip)

**Comment by rsuter** [comment]
please report any problems

**Comment by rsuter** [comment]
Ok no, it is not really working...

**Comment by rsuter** [comment]
It seems that it breaks when you have .NET Core (i.e. new MSBuild) projects in your solution. Just unload them first...

**Comment by rsuter** [comment]
Because I need a verified account on VS marketplace, i cannot publish the extension yet. Here the latest release build: 

[NuGetReferenceSwitcher.zip](https://github.com/rsuter/NuGetReferenceSwitcher/files/900272/NuGetReferenceSwitcher.zip)

**Comment by niemyjski** [comment]
@rsuter you should just be able to upload your extension in place of the existing one. I don't know why you'd need to be verified (I don't remember being verified for our extension). If you want to send out a tweet to dave kean / VS twitter account and put a link here I'll retweet.

**Comment by rsuter** [comment]
As you can see, I have an extension for each VS version (2012, 2013, 2015) and I need to publish a new one for VS 2017...

**Comment by niemyjski** [comment]
You can reuse the vsix package (extension name) for multiple versions of
visual studio. In the pkgdef you just put your supported versions.

Thanks
-Blake Niemyjski

**Comment by rsuter** [comment]
Good idea, do you have the time for a pr?

**Comment by niemyjski** [comment]
If I can get some time I will, I'm swamped pretty bad right now :(

**Comment by rsuter** [comment]
https://marketplace.visualstudio.com/vsgallery/ef35a0f9-2712-4634-97e0-51c03f4be1e3
