### ISSUE TITLE
Keyboard Input Inconsistent related to "an operation is blocking user input"

### ISSUE THREAD

**Issue by ChristopherElliott** [rsuter/NuGetReferenceSwitcher#3]
I've noticed that when I use the tool, I get in a state where certain types of input are no longer possible. 

For example, I'll be able to type characters but not cut & paste or be unable to delete characters. 

I've also noticed that this message is displayed consistently when I close visual studio after getting into this state: 

![image](https://cloud.githubusercontent.com/assets/1360605/8315563/79d0e88a-19a6-11e5-9d62-fa3b903e70f8.png)
Text of image says: "Microsoft Visual Studio has detected that an operation is blocking user input. This can be caused by an active modal dialog or a task that needs to block user interaction. Would you like to shut down anyway?"

**Comment by rsuter** [comment]
Can you check your

`C:\Users\USER\Documents\Visual Studio 2013`

directory, and post the corresponding `crash_*` file here?

**Comment by rsuter** [comment]
Also please search for an NuGetReferenceSwitcher exception in the VS ActivityLog.xml: 

`C:\Users\USER\AppData\Roaming\Microsoft\VisualStudio\12.0\ActivityLog.xml`

**Comment by Christopher1065** [comment]
No luck on either. There are no crash_* files and the only activity in my ActivityLog.xml is from over a month ago and no mention of NuGetReferenceSwitcher. Attaching the debugger didn't catch any exceptions related to the popup though there were plenty of First-chance exceptions that may or may not be related.

**Comment by rsuter** [comment]
Can you check if you still have the problem with the just released v1.3?

**Comment by ivanovAndrei** [comment]
I just downloaded the 1.3 release from https://visualstudiogallery.msdn.microsoft.com/68878c27-110c-43ec-ae61-3ea3f7aae88c which is where the release is pointing to.
Note: When using that link to download for VS2013, The "About" screen shows:
Version: 1.1.5672.31298, 7/13/2015
Running with VS2013 premium

I still have this issue, and no crash file is present. I get this consistently every time I switch references.
When I go to Close VS, Sometimes what I see is a dialog prompting me to save one of the projects in a solution (even though I clicked on solution file and saved it).

**Comment by rsuter** [comment]
Version: 1.1.5672.31298, 7/13/2015 is the newest release, I forgot to update the version there...
Strange, I tested it in my Visual Studio and it worked. Can you debug the extension to find the problem?

**Comment by ivanovAndrei** [comment]
Having never done it, I'm not sure I have the time to go figure out how to load it up in debug mode, etc. I can run a debug build of it and send you logs, if you can build one for me.

**Comment by MrDoomBringer** [comment]
I and my coworkers have gotten this exact same issue when we're attempting to use the plugin for VS2013 and multiple nuget packages. I don't have time right now to manually debug the issue but I'd imagine it's related to a dialog not being properly closed. It seems that modifier keys, such as control or shift are the ones directly affected by the issue.

Restarting visual studio makes everything work until I switch references again, at which point I must perform another restart.

**Comment by rsuter** [comment]
Should be fixed in v1.5, can someone verify?

**Comment by MrDoomBringer** [comment]
I installed the update from the VS Extension Gallery and immediately encountered #11. I've reverted to my personal build for the time being which does not have the same problem.

**Comment by MrDoomBringer** [comment]
The latest version is confirmed working for VS2013.

**Comment by rsuter** [comment]
Ok thx
