### ISSUE TITLE
Visual Studio 2022

### ISSUE THREAD

**Issue by DatasoftNetwork** [rsuter/NuGetReferenceSwitcher#55]
Will this project be updated to support Visual Studio 2022? We still use it in our older projects.

**Comment by BigHoss** [comment]
I would recommend using dnt with a powershell script. [dnt](https://github.com/RicoSuter/DNT#switch-to-projects)

**Comment by RicoSuter** [comment]
Extension is not under active development and replaced by DNT: 
https://github.com/RicoSuter/DNT#switch-to-projects
