### ISSUE TITLE
Visual studio 2022 version

### ISSUE THREAD

**Issue by pkatsourakis** [rsuter/NuGetReferenceSwitcher#57]
Upgdade this extension to work in Visual Studio 2022

[Docs - Update a Visual Studio extension for Visual Studio 2022](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022)

**Comment by RicoSuter** [comment]
This extension is not being worked on actively. Please use DNT instead: 
https://github.com/RSuter/DNT
